const DATA = {
  sekolah: {
    nama: "SMAN 1 Kudus",
    alamat:
      "Jl. Pramuka No.41, Nganguk, Mlati Lor, Kec. Kota Kudus, Kabupaten Kudus, Jawa Tengah 59319",
    telp: "(0291) 431368",
  },
  visi: "Terbentuknya warga sekolah yang berkarakter, unggul dalam Ilmu Pengetahuan dan Teknologi, mampu bersaing secara global, cinta lingkungan dan berwawasan budaya bangsa.",
  misi: [
    "Membentuk peserta didik yang beriman, bertakwa kepada Tuhan Yang Maha Esa, dan berakhlak.",
    "Membentuk peserta didik yang mampu bernalar kritis dan kreatif, unggul dalam menguasai ilmu pengetahuan dan teknologi.",
    "Mengembangkan kemandirian peserta didik melalui pembiasaan, kewirausahaan, dan pengembangan diri yang terencana dan berkesinambungan agar mampu bersaing secara global.",
    "Mengembangkan sikap dan perilaku warga sekolah yang cinta dan peduli terhadap kelestarian lingkungan.",
    "Membentuk peserta didik yang peduli terhadap kebhinekaan global, semangat bergotong-royong, dan berwawasan budaya bangsa.",
  ],
  sejarah: [
    "SMA Negeri 1 Kudus berdiri sejak 1 Agustus 1960 berdasarkan SK Menteri Pendidikan dan Kebudayaan RI tanggal 24 Juni 1960 nomor 191/S.K/B.III. Awalnya sekolah menumpang di Asrama Militer Jati dengan tiga jurusan: A (sastra), B (ilmu pasti), dan C (ekonomi). Peresmian dilakukan pada 17 Agustus 1960 oleh Letkol Mudigdo, Danrem 073 Makutarama Salatiga.",
    "Pimpinan pertama adalah Soewito Hadisoemitro. Pada November 1960 sekolah sempat menumpang di gudang Muriatex, hingga akhirnya dibangun gedung sendiri di Desa Mlati (kini Jl. Pramuka) sebagai satu-satunya SMA di Kota Kudus.",
    "Seiring waktu, jumlah kelas berkembang dari 23 menjadi 30 kelas. Sekolah pernah meraih juara 3 tingkat internasional lomba KIR dan juara 1 nasional pada 2001, dengan sekitar 80% lulusan diterima di perguruan tinggi negeri. Pada 2003/2004 sekolah memperoleh predikat memuaskan dari Badan Akreditasi Nasional.",
    "Kepemimpinan sekolah telah berganti belasan kali, dari Soewito Hadisoemitro hingga Drs. Sudiharto, M.A.P. (definitif sejak 2022). Saat ini sekolah dipimpin Nur Afifuddin, S.Pd., M.Pd. sebagai Plt. Kepala Sekolah.",
  ],
  guru: [
    ["Nur Afifuddin, S.Pd., M.Pd.", "Plt. Kepala Sekolah", "Pimpinan"],
    ["Daviq Prasetian, S.Pd", "Waka Kurikulum", "Pimpinan"],
    [
      "Yosy Setyaji, S.Pd",
      "Waka Sarpras / Guru Pendidikan Pancasila",
      "Pimpinan",
    ],
    ["Reko Prasojo", "Waka Humas", "Pimpinan"],
    ["Sulistyani, S.Pd., M.Pd", "Waka Kesiswaan", "Pimpinan"],
    ["Drs. Eko Nur Budi, M.Pd", "Guru Bahasa Indonesia", "Guru"],
    ["Drs. Hasan Mahmud, M.Pd", "Guru BK", "Guru"],
    ["Drs. Imam Santosa, M.Or", "Guru Olah Raga", "Guru"],
    ["Muh Prayetno, S.Ag., M.S.I", "Guru Agama", "Guru"],
    ["Rr. Mustika Sri Rejeki, S.Pd", "Guru Fisika", "Guru"],
    ["Indriati Sukorini, S.Pd., M.Pd", "Guru Matematika", "Guru"],
    ["Triastuti Evawani, S.Pd., M.Pd", "Guru Biologi", "Guru"],
    ["Yasir, S.Pd., M.Pd", "Guru Bahasa Indonesia", "Guru"],
    ["Dra. Ida Sulistyani", "Guru BK", "Guru"],
    ["Noor Rina Kastatria, S.Pd", "Guru Bahasa Indonesia", "Guru"],
    ["Metri Junaedi, S.Pd., M.Pd", "Guru Fisika", "Guru"],
    ["Shofyatul Ulya Dwiyana, S.Pd.", "Guru Bahasa Inggris", "Guru"],
    ["Akhirul Riyad, M.Pd", "Guru Olah Raga", "Guru"],
    ["Teguh Prasojo, S.Pd., M.Pd", "Guru Matematika", "Guru"],
    ["Abdul Azis, S.Pd", "Guru Kimia", "Guru"],
    ["Retno Ulliyah, S.Pd", "Guru Matematika", "Guru"],
    ["Puji Astuti, S.Pd", "Guru Biologi", "Guru"],
    ["Noor Taufiq, S.Pd", "Guru Matematika", "Guru"],
    ["Moh. Muchlas, S.Pd., M.Pd", "Guru Seni Rupa", "Guru"],
    ["Sri Rejeki, S.Pd", "Guru Bahasa Inggris", "Guru"],
    ["Endarta, S.Pd., M.Or", "Guru Olah Raga", "Guru"],
    ["Mustafa Hizkia S, S.Th., M.Pd.K", "Guru Agama Kristen", "Guru"],
    ["Siti Rokhanah, S.Pd", "Guru Fisika", "Guru"],
    ["Noor Hidayati, S.Pd., M.Pd", "Guru Matematika", "Guru"],
    ["Kasiati, S.Pd", "Guru Bahasa Inggris", "Guru"],
    ["Hanum Salimah, S.Pd", "Guru BK", "Guru"],
    ["Ari Wijaya, S.Kom", "Guru TIK", "Guru"],
    ["Eni Susianti, S.Pd.", "Guru Kimia", "Guru"],
    ["Raden Heriyanto Irawan, S.Pd", "Guru Bahasa Inggris", "Guru"],
    ["Farida, S.Pd.", "Guru Bahasa Inggris", "Guru"],
    ["Sri Kanti, SS", "Guru Bahasa Jawa", "Guru"],
    ["Lutfi Ari Sandi, S.Kom", "Guru TIK", "Guru"],
    ["Wiwik Qomariyah, S.Pd.I.", "Guru Agama Islam", "Guru"],
    ["Bagus Pambajeng Noor P, S.Pd", "Guru Sejarah", "Guru"],
    ["Norariska Nalurita, S.Pd", "Guru Sosiologi", "Guru"],
    ["Sulfia Indriastuti, S.Kom", "Guru TIK", "Guru"],
    ["Palupi Etikawati, S.Pd", "Guru BK", "Guru"],
    ["Yunita Anggraini, S.Psi", "Guru BK", "Guru"],
    ["Lukman Darul Fuadi, S.Pd", "Guru Geografi", "Guru"],
    ["Dartik, S.Pd", "Guru Pendidikan Pancasila", "Guru"],
    ["Heru Irawan, S.Kom", "Guru TIK", "Guru"],
    ["Hafidh Syifaunnur, S.Pd", "Guru Kimia", "Guru"],
    ["Pramita Apriliyana, S.Pd", "Guru Bahasa Jawa", "Guru"],
    ["Hery Supriyadi, S.Pd", "Guru Olah Raga", "Guru"],
    ["Mei Wulan Sari, S.Pd", "Guru Bahasa Jawa", "Guru"],
    ["Ayu Candra Permana Sari, S.Pd", "Guru Pendidikan Pancasila", "Guru"],
    ["Galuh Winda Olief, S.Pd", "Guru Seni Tari", "Guru"],
    ["Eko Sarwono, S.Pd.", "Guru Matematika", "Guru"],
    ["Sri Mulyani, S.Pd.", "Guru Matematika", "Guru"],
    ["Fauzul Muna, S.Pd.", "Guru Ekonomi", "Guru"],
    ["Lita Hanna Failasufa, S.Pd.", "Guru Sosiologi", "Guru"],
    ["Dra. Munawwaroh", "Guru Biologi", "Guru"],
    ["Solikan, S.Pd", "Guru Fisika", "Guru"],
    ["Mochammad Galih Sulistyo, S.Pd.", "Guru Sejarah", "Guru"],
    ["Andi Pujianto, S.Pd.", "Guru Ekonomi", "Guru"],
    ["Muhamad Wahono, S.Pd.I., M.Pd", "Guru Agama", "Guru"],
    ["Siti Mudrikah, S.Pd", "Guru Bahasa Jawa", "Guru"],
    ["Harjito Tri Khamdhani, S.Pd.", "Guru BK", "Guru"],
    ["Zahratun Nisa', S.Pd.", "Guru Bahasa Prancis", "Guru"],
    ["Ahmad Fathul Hakim, S.Pd.I, M.Pd", "Guru Agama Islam", "Guru"],
    ["Aditya Dwi Prasetya, S.Pd.", "Guru BK", "Guru"],
    ["Didik Ardiato, S.Pd.", "Guru Geografi", "Guru"],
    ["Hesti Galang Purnama Siwi, S.Pd.", "Guru Sejarah", "Guru"],
    ["Ery Purnamawati, S.Pd.", "Guru Bahasa Indonesia", "Guru"],
    ["Indria Prastiwi Sari, S.Pd.", "Guru Bahasa Indonesia", "Guru"],
    ["Rifa Irwan Sani, S.Pd.", "Guru Sejarah", "Guru"],
    ["Luky Eriyanti, S.Pd", "Guru Sejarah", "Guru"],
    ["Ainunnisa Nalini Wulandari, S.Pd.", "Guru Biologi", "Guru"],
    ["Devingga Kurnia Dewi, S.Pd.", "Guru Sejarah", "Guru"],
    ["Ratri Kusumarini, S.Pd., M.Pd", "Guru Bahasa Indonesia", "Guru"],
    ["Titi Aditiasari Dewi, S.Pd., M.Pd", "Guru Matematika", "Guru"],
    ["Anisa Tri Subekti, S.Pd.", "Guru Sosiologi", "Guru"],
    ["Tiara Dwi Syania, S.Pd.", "Guru Sosiologi", "Guru"],
    [
      "Jami'atun, S.I.P",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Toufiq, S.I.P.",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Istiyanah, S.I.P.",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    ["Solichin", "Staff Tata Usaha & Karyawan", "Staf Tata Usaha & Karyawan"],
    ["Sukarno", "Staff Tata Usaha & Karyawan", "Staf Tata Usaha & Karyawan"],
    [
      "Moch. Solikhin, A.Md",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Aris Rahmawan, A.Md",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Agus Sudirno, S.E",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    ["Eko Samuji", "Staff Tata Usaha & Karyawan", "Staf Tata Usaha & Karyawan"],
    [
      "Saiful Amri",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Agus Setyawan",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Jauhar Fahdida, S.Kom",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Bayu Faizal Supriyadi",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    ["Sugiyono", "Staff Tata Usaha & Karyawan", "Staf Tata Usaha & Karyawan"],
    [
      "Ari Purnomo",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
    [
      "Wahyu Prasetyo, S.Kom",
      "Staff Tata Usaha & Karyawan",
      "Staf Tata Usaha & Karyawan",
    ],
  ],
  berita: [
    {
      slug: "launching-kkri",
      tanggal: "2026-09-24",
      gambar: "berita-1.png",
      judul:
        "SMA Negeri 1 Kudus Kirim Lima Siswa dalam Launching Ekstrakurikuler KKRI",
      ringkasan:
        "Lima siswa mewakili sekolah dalam launching Komunitas Kebangsaan dan Kedisiplinan Remaja Indonesia (KKRI).",
      isi: [
        "SMA Negeri 1 Kudus berpartisipasi dalam launching ekstrakurikuler Komunitas Kebangsaan dan Kedisiplinan Remaja Indonesia (KKRI) pada Rabu, 23 September 2026 pukul 10.00 WIB di ruang TRRC. Sekolah mengirimkan lima siswa serta beberapa wakil pimpinan sekolah.",
        "Menurut Dandim Kudus, KKRI menjadi momentum membangun karakter generasi muda yang berkepribadian kuat, disiplin, serta berwawasan kebangsaan. Melalui kegiatan ini siswa diharapkan menumbuhkan nilai kebangsaan, tanggung jawab, dan gotong royong menuju Indonesia Emas 2045.",
      ],
    },
    {
      slug: "juara-karnaval-budaya",
      tanggal: "2026-09-24",
      gambar: "berita-2.png",
      judul:
        "Puncak HUT ke-477 Kudus, SMA Negeri 1 Kudus Raih Juara dalam Parade Karnaval Budaya",
      ringkasan:
        "Kontingen SMASA menerima penghargaan Juara 1 Karnaval Budaya di Pendopo Kabupaten Kudus.",
      isi: [
        'Dalam rangkaian puncak HUT Kudus, perwakilan SMA Negeri 1 Kudus menerima penghargaan atas Juara 1 Karnaval Budaya lewat tema "Berkah Wuwu, Leladi Panguripan Desa Kesambi" yang memadukan sejarah, kearifan lokal, dan seni pertunjukan.',
        "Piala diserahkan di Pendopo Kabupaten Kudus oleh Bupati dan Wakil Bupati Kudus kepada guru pendamping Nur Afifuddin, S.Pd., M.Pd., Ratri Kusumarini, S.Pd., M.Pd., dan Galuh Winda Olief, S.Pd.",
      ],
    },
    {
      slug: "pilketos-2026",
      tanggal: "2026-09-16",
      gambar: "berita-3.png",
      judul:
        "Demokrasi di Sekolah: Antusiasme Siswa SMA Negeri 1 Kudus Rayakan Pilketos 2026",
      ringkasan:
        "Pemilihan Ketua dan Wakil Ketua OSIS berlangsung tertib dan antusias.",
      isi: [
        "Pada Rabu (16/9/2026), SMA Negeri 1 Kudus menggelar Pilketos Periode 2026 yang diikuti siswa kelas X hingga XII secara Langsung, Umum, Bebas, dan Rahasia (LUBER), dibuka dengan sambutan Waka Kesiswaan Mustafa Hizkia dan Pembina OSIS Mohamad Wahono.",
        "Hasil penghitungan suara terbuka memenangkan Paslon nomor 1, Zayeda Qitarah F. (XI F-10) dan Raditya Putra A. (XI F-11). Pilketos menjadi bukti nilai demokrasi dipraktikkan langsung oleh pelajar.",
      ],
    },
    {
      slug: "perjuangan-karnaval",
      tanggal: "2026-09-14",
      gambar: "berita-4.png",
      judul:
        "Perjuangan di Balik Gemerlap Karnaval: Persembahan Juara dari SMA Negeri 1 Kudus",
      ringkasan:
        "Kisah perjuangan kontingen SMASA hingga meraih Juara 1 Tingkat Umum.",
      isi: [
        'Pada Sabtu (12/9/2026), Karnaval Budaya Kota Kudus dalam rangka HUT ke-477 berlangsung meriah. Kontingen SMASA mencuri perhatian dengan tema "Berkah Wuwu, Leladi Panguripan Desa Kesambi" dan meraih Juara 1 Tingkat Umum.',
        'Perjuangan dimulai sejak pukul 10.00 WIB ketika guru pembimbing merapikan barisan dan koreografi, sementara siswa mulai berias pukul 11.00 WIB dengan busana bertema "Berkah Wuwu".',
      ],
    },
    {
      slug: "orasi-debat-osis",
      tanggal: "2026-09-16",
      gambar: "berita-5.png",
      judul:
        "Orasi dan Debat Calon Ketua & Wakil Ketua OSIS SMAN 1 Kudus Periode 2026/2027",
      ringkasan:
        "Tiga pasangan calon menyampaikan orasi dan beradu gagasan dalam sesi debat.",
      isi: [
        "Pada 10 September 2026, seluruh warga sekolah mengikuti orasi dan debat calon Ketua dan Wakil Ketua OSIS 2026/2027. Acara dibuka dengan doa, lagu Indonesia Raya, dan Mars SMASA.",
        "Tiga paslon tampil: nomor 01 Zayeda Qitarah Fazma dan Raditya Putra Afandi, nomor 02 Keisha Aufa Hasna dan Ovan Alaska Putra D., serta nomor 03 Roro Harmeysha Aiko Nabila Siham dan Pascalis Nathanael Lucky Wardhana. Sesi debat terbagi menjadi tiga segmen bertema berbeda.",
      ],
    },
    {
      slug: "juara-3-kiv-fest",
      tanggal: "2026-09-14",
      gambar: "berita-6.png",
      judul: "SMAN 1 Kudus Raih Juara 3 di KIV FEST 2026",
      ringkasan:
        "Video pendek antikorupsi karya siswa meraih Juara 3 Kudus Integrity Video Festival.",
      isi: [
        'Pada 14 September 2026, SMA Negeri 1 Kudus meraih Juara 3 Kudus Integrity Video Festival (KIV FEST) 2026 yang digelar Inspektorat Kabupaten Kudus bertema "Dari Layar Kecil, Dampak Besar untuk Integritas".',
        "Sekolah mengutus 3 kelompok. Tim yang dipimpin Rico Gustaf Aulia (XI F-03) mengemas pesan kejujuran dan penolakan korupsi dalam video berdurasi satu menit.",
      ],
    },
  ],
  prestasi: [
    {
      t: "2026-09-14",
      lomba: "Kudus Integrity Video Festival (KIV FEST) 2026",
      peringkat: "Juara 3",
      peraih: "Rico Gustaf Aulia (XI F-03) dan tim",
      info: "Kudus · 2026",
    },
    {
      t: "2026-09-12",
      lomba: "Karnaval Budaya HUT ke-477 Kudus",
      peringkat: "Juara 1",
      peraih: "Kontingen SMA Negeri 1 Kudus",
      info: "Tingkat Umum · 2026",
    },
    {
      t: "2025-09-24",
      lomba: "Story Telling Competition, English Festival Esa UMK 2025",
      peringkat: "Juara 1",
      peraih: "Juanaya Hayu Rembonette",
      info: "Kudus · 2025",
    },
    {
      t: "2025-09-06",
      lomba: "English Student Association UMK 2025",
      peringkat: "Juara 2",
      peraih: "Raissa dan Alanis",
      info: "Kudus · 2025",
    },
    {
      t: "2025-09-05",
      lomba: "Renang Gaya Dada 50, 100, 200 Meter",
      peringkat: "Juara 1",
      peraih: "Melinda Priskila Ariska",
      info: "Tingkat Provinsi · 2025",
    },
  ],
};
